61 individual feedback
CSPS-RIW/Vue_QuizGen-riw-patches pull request #65
Opened 2024-01-19 18:10 UTC by noamstul

Adds the option for individual feedback, currently **only for Multiple Select question types**

SR only -- rereads their responses, tells them what they selected, and tells them if it was correct or incorrect, EN & FR working

2024-01-19 19:34 UTC, r-torres-csps requested changes
Check #66 for my suggested changes wich are:

`RM instructions, rm aria-live attr, add p tags to sr-feedback`

I already made the changes in that branch.

2024-01-19 19:34 UTC, r-torres-csps commented on public/m1-7_en.txt
good

2024-01-19 19:34 UTC, r-torres-csps commented on public/m1-7_fr.txt
good, will update with proper text

2024-01-19 19:34 UTC, r-torres-csps commented on src/App.vue
All good to me

2024-01-19 19:34 UTC, r-torres-csps commented on src/components/Question.vue
RM instructions, rm aria-live attr, add p tags to sr-feedback. Check #66 to improve code

2024-01-23 12:26 UTC, r-torres-csps commented
## Question 2 shows generic feedback by default
I have not selected any options in the second question and it shows the generic feedback without icons. It looks the same in both EN and FR. 
![image](https://github.com/CSPS-RIW/Vue_QuizGen-riw-patches/assets/76488409/26da93c3-3e05-4511-b9c0-ebfac76eef07)

2024-01-23 15:04 UTC, noamstul commented
> ## Question 2 shows generic feedback by default
> I have not selected any options in the second question and it shows the generic feedback without icons. It looks the same in both EN and FR. ![image](https://private-user-images.githubusercontent.com/76488409/298939412-26da93c3-3e05-4511-b9c0-ebfac76eef07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTg3NTQsIm5iZiI6MTcwNjAxODQ1NCwicGF0aCI6Ii83NjQ4ODQwOS8yOTg5Mzk0MTItMjZkYTkzYzMtM2UwNS00NTExLWI5YzAtZWJmYWM3NmVlZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0MDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZGQzZDFmNjkzMzcyZTk3YmQwN2QzYWFjNTE4NzhhNmI0NDU1ZmMwNjEwZmE3YmRhODA4MDllODhmNzg2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WcwaQudO-v1GYCsBDS9fflLrPw4tFzq5LjW2bYTbiAg)

Resolved

2024-01-23 15:33 UTC, r-torres-csps approved these changes
Looks good

2024-01-23 16:39 UTC, merged